### PR TITLE
Port to GTK4

### PR DESCRIPTION
**Pull request by taozuhong**
Port all code to GTK4, hope it can make it ready for GTK4 quickly.

### CODE REVIEW

**Comment by taozuhong** [comment]
All codes have been ported to GTK4, compiled successfully, but have not yet execute normally.

**Comment by taozuhong** [comment]
All codes have been ported to GTK4, compiled successfully, but have not yet run normally.

**Comment by taozuhong** [comment]
All completed.

**Comment by lcallarec** [comment]
Not sure about how many systems have GTK4 installed vs GTK3.
@stsdc : do you think switching to GTK4 is something good for your monitor application ? Or do you think that we should have 2 different builds / flavor for GTK3 & 4 ?

**Comment by lcallarec** [comment]
P.S. thanks @taozuhong for your PR :)

**Comment by stsdc** [comment]
Right now Monitor is still on GTK3, I'm waiting elementary os to switch to newer base with GTK4 support.
If possible, I would like to have one last GTK3 release of live-chart. I 'd like to see live-chart moving forward, therefore, I do not think that supporting two flavors will be efficient.

**Comment by lcallarec** [comment]
Fine ! @taozuhong I'll merge this PR when @stdc monitor app will be ready to move on GTK4.

**Comment by taozuhong** [comment]
Honor to get it.

**Comment by stsdc** [comment]
I'm ready to move to GTK4. This can be merged!

**Comment by stsdc** [comment]
@lcallarec  pretty please :pleading_face:

**Comment by lcallarec** [comment]
Merged into master.  Thanks @taozuhong for your contribution, and @stsdc for your patience :)
I'm preparing a proper new release for live-chart.

**Comment by stsdc** [comment]
Thank you! ✨👍

**Pull request merged**
