### PR TITLE
Support to build dynamic library and fix compile error

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by lcallarec** [comment]
Thanks for your contribution @taozuhong !

And thanks for the tip about MSYS2 compilation :)

Just a question about the shared / dynamic library : can't you just compile / link it directly against your app ? For my own knowledge, can you explain the use case ?

Thanks !

**Comment by taozuhong** [comment]
yeah, static library is ok for me, just want to make it independent

BTW, link static library yet not command for me, so add dynamic library support.

**Comment by lcallarec** [comment]
Ok @taozuhong, I think I get the gist. I'm not aware about MINGW or similar Windows stuff, so thank you for your precious contribution !

**Comment by taozuhong** [comment]
My pleasure.

**Comment by taozuhong** [comment]
image

@lcallarec

**Pull request merged**
