### PR TITLE
Feature sliding timeline

### PR DESCRIPTION
**Pull request by Robert-Ordis**
Makes x-axis timeline sliding(scrollable) with the serie.

- Currently, I'm thinking how to test this. (Calculate the pos of gridline and pick its color up ?>

### CODE REVIEW

**Comment by Robert-Ordis** [comment]
Is there any idea what should I do to ? xo

**Comment by Robert-Ordis** [comment]
@lcallarec 
I tried to write the test of this.
Is this right ?

**Comment by lcallarec** [comment]
Sorry, was in long holydays :)

Outside the small typo in the documentation, looks good !

**Comment by Robert-Ordis** [comment]
Fixed it. xo

**Comment by lcallarec** [comment]
Thanks @Robert-Ordis !

**Comment by Robert-Ordis** [comment]
> Thanks @Robert-Ordis !

Thx 4 your merging.
I'll prepare for the next PR.
Happy New Year!

**Pull request merged**
