### PR TITLE
features for timeline.

### PR DESCRIPTION
**Pull request by Robert-Ordis**
First, I'm sorry for committing 3 changes in this one PR.
This has changes about manipulating the timeline.

- Seeking on the timeline
- Pausing the timeline (but chart will be refreshed)
- timeline formatting: be able to print the fractional part→Configuring on x_axis may be better rather than this.

### CODE REVIEW

**Comment by Robert-Ordis** [comment]
@lcallarec 
That's all of mods on this part.
I'll submit the next PR after getting the disicion for this.

**Comment by lcallarec** [comment]
I'm glad to see this PR, kudos @Robert-Ordis ^^

Technically, it looks good. I will test very soon this feature on a real environment.

If everything is ok on a functional point of view, outside my small comment, I will merge this PR.

If you got time to improve this code in the future, I'll suggest you to :

* Add test for `TimeSeek` class , especially the `get_time_str` method; if you're not confortable with testing, I can mentor you ;
* Hide behind an abstraction how the timeseek is working : for exemple, instead of `chart.config.time.current = GLib.get_real_time() / chart.config.time.conv_ms;`, it will be better to have, for example : 
```vala
chart.config.time.now();
```
* IMHA, public properties `conv_us`, `conv_ms`, `conv_sec` should stay hidden from the oustide.

Anyway, that not blocking at all.

Thank you !

**Comment by Robert-Ordis** [comment]
Dear, @lcallarec 
Thank you for your reviewing.

I'm so happy for your evaluation...lol

Yes, your pointing about abstraction is right.
Excuse me to this, my app is using timeseek heavily from seekbar, then specifying actual timepoint is needed.
Alternative idea might be here.
`chart.config.time.from_ms(unix_time_ms)`

OK, I'll try to make a testcode for it. thank you so much.

**Comment by Robert-Ordis** [comment]
Excuse me to additional commit.
I found some problem in my code and fixed them.

Inside story: On my app(https://github.com/Robert-Ordis/omni-plotter), I'm thinking that treating time in microsec might be needed in the future.

**Comment by lcallarec** [comment]
I just tested your PR, it works like a charm :)

Please fix the documenation issue I noticed earlier and your PR will be merged (up to you to improve the basecode according to my previous recommendations in another PR later)

**Comment by Robert-Ordis** [comment]
I pushed documentation mod (mainly related to dropped property and config.time.set_range)

> Please fix the documenation issue I noticed earlier

Please tell me what the issue you noticed is.

**Comment by lcallarec** [comment]
The (small) documentation issue is here : https://github.com/lcallarec/live-chart/pull/38/files/0cd13fdd75f63d05e8cad992b1b25fcd02aaa72c#diff-3a1bd79644f8f66a114a45997f889dcba1ca809b0bb65865d4d7117ddc3e023fR32

As a rule of thumb, if a property / attribute / method is public and is meant to be used by a developper outside the project, it should be documented.

The suggestions I was talking about : https://github.com/lcallarec/live-chart/pull/38#issuecomment-1333453921, but it could be done later, it's not blocking)

**Comment by Robert-Ordis** [comment]
About `config.time.show_fraction` ?
I see. But give me a little time to modify code.
I thought it should be on `config.x_axis` because it changes a format of timepoint printed in x-axis.

**Comment by Robert-Ordis** [comment]
I'm sorry for keeping changing public part...
By the way, I wrote it as x_axis setting.

**Comment by lcallarec** [comment]
Good to merge !
That's a great feature that will add lots of value to live-chart. Thanks @Robert-Ordis for this one !

**Comment by Robert-Ordis** [comment]
Thank you very much for your reviewing.
Then, I'll go on the next PR work after getting home.

There are still 9 works for comitting PR... lol

**Comment by lcallarec** [comment]
Don't forget, for your futur PR, to add appropriate tests. Please note that you should test the business logic, but also the rendering (i.e. what the user is seeing on the screen, have a look at https://github.com/lcallarec/live-chart/blob/master/tests/smooth_line_area.vala#L3).

**Pull request merged**
